### ISSUE TITLE
can't 'go run onionscan.go'

### ISSUE THREAD

**Issue by bonda007** [s-rah/onionscan#56]
user@ubuntu:~/go/src/github.com/s-rah/onionscan$ go run onionscan.go
# golang.org/x/crypto/ed25519
/home/user/onion/src/golang.org/x/crypto/ed25519/ed25519.go:54:66: error: reference to undefined identifier ‘crypto.SignerOpts’
 func (priv PrivateKey) Sign(rand io.Reader, message []byte, opts crypto.SignerOpts) (signature []byte, err error) {
                                                                  ^
lool@ubuntu:~/go/src/github.com/s-rah/onionscan$

**Comment by s-rah** [comment]
I think this is a version issue, since crypto.SignerOpts is in the standard library. What is the value of `go version`?

I may need to update the x/crypto libraries e.g. `go get -u golang.org/x/crypto/ed25519`

**Comment by bonda007** [comment]
`go version`

go verison xgcc (Ubunto 4.9.3-0ubunto4) 4.9.3 linux/amd64

**Comment by s-rah** [comment]
It looks like you have cgo installed under go instead of the golang check out this issue https://github.com/golang/go/issues/15429 - On Ubuntu the name of the go distribution is golang-go.

**Comment by s-rah** [comment]
Its been over a month since the last update on this, I'm going to assume this is fixed until proved otherwise  - I have document this error on the wiki for now, in lieu of a more complete documentation solution: https://github.com/s-rah/onionscan/wiki#errors-running-onionscan

**Comment by ccc-cc** [comment]
Like the wiki says, the error disappears in go 1.7. Debian Jessie ships go 1.3 but luckily, go 1.7 backport is available, which works nicely: https://packages.debian.org/jessie-backports/amd64/golang-go

**Comment by zerocod3r** [comment]
It doesn't works with go 1.6 and 1.7 as it have some packages issue, works well with go1.9.
Please resolve this issue
[https://github.com/s-rah/onionscan/issues/158](url)

**Comment by naba967** [comment]
- go get github.com/HouzuoGuo/tiedot
- go get golang.org/x/crypto/openpgp
- go get golang.org/x/net/proxy
- go get golang.org/x/net/html
- go get github.com/rwcarlsen/goexif/exif
- go get github.com/rwcarlsen/goexif/tiff
